### ISSUE TITLE
Execution failed for task ':client-app:bootRun'. > Process 'command 'C:\Program Files\Java\jdk1.8.0_161\bin\java.exe'' finished w ith non-zero exit value 1

### ISSUE THREAD

**Issue by suyash796** [frankiesardo/icepick#125]
hello 
this was working when i used it before but now its showing this error 
please help 
-----------
user variable path - C:\Program Files\Java\jdk1.8.0_161\bin;C:\Users\SUYASH\AppData\Roaming\npm
system variable path - C:\Program Files\Java\jdk1.8.0_161\bin;C:\Program Files\nodejs\
---------------------------
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\SUYASH\Downloads\Compressed\code2.1\medical-gov>gradlew client:bootRun
Starting a Gradle Daemon, 1 busy and 2 incompatible and 1 stopped Daemons could
not be reused, use --status for details
:shared-library:compileJava
Note: C:\Users\SUYASH\Downloads\Compressed\code2.1\medical-gov\shared-library\sr
c\main\java\com\codesnbugs\shared\bo\ImageRequest.java uses or overrides a depre
cated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\SUYASH\Downloads\Compressed\code2.1\medical-gov\shared-library\sr
c\main\java\com\codesnbugs\shared\util\JwtUtil.java uses unchecked or unsafe ope
rations.
Note: Recompile with -Xlint:unchecked for details.
:shared-library:processResources UP-TO-DATE
:shared-library:classes
:shared-library:jar
:spring-security:compileJava
:spring-security:processResources UP-TO-DATE
:spring-security:classes
:spring-security:jar
:client-app:compileJava
:client-app:processResources
:client-app:classes
:client-app:findMainClass
:client-app:bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

2018-08-31 12:23:15.243  INFO 6664 --- [           main] com.codesnbugs.clientAp
p.Application     : Starting Application on SUYASH-PC with PID 6664 (C:\Users\SU
YASH\Downloads\Compressed\code2.1\medical-gov\client-app\build\classes\main star
ted by SUYASH in C:\Users\SUYASH\Downloads\Compressed\code2.1\medical-gov\client
-app)
2018-08-31 12:23:15.249  INFO 6664 --- [           main] com.codesnbugs.clientAp
p.Application     : No active profile set, falling back to default profiles: def
ault
2018-08-31 12:23:15.871  INFO 6664 --- [           main] ationConfigEmbeddedWebA
pplicationContext : Refreshing org.springframework.boot.context.embedded.Annotat
ionConfigEmbeddedWebApplicationContext@3a4621bd: startup date [Fri Aug 31 12:23:
15 IST 2018]; root of context hierarchy
2018-08-31 12:23:27.752  INFO 6664 --- [           main] s.b.c.e.t.TomcatEmbedde
dServletContainer : Tomcat initialized with port(s): 8082 (http)
2018-08-31 12:23:27.835  INFO 6664 --- [           main] o.apache.catalina.core.
StandardService   : Starting service [Tomcat]
2018-08-31 12:23:27.837  INFO 6664 --- [           main] org.apache.catalina.cor
e.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.23
2018-08-31 12:23:28.240  INFO 6664 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[loc
alhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-08-31 12:23:28.244  INFO 6664 --- [ost-startStop-1] o.s.web.context.Context
Loader            : Root WebApplicationContext: initialization completed in 1238
8 ms
2018-08-31 12:23:29.380  INFO 6664 --- [ost-startStop-1] o.s.b.w.servlet.FilterR
egistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-08-31 12:23:29.381  INFO 6664 --- [ost-startStop-1] o.s.b.w.servlet.FilterR
egistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-08-31 12:23:29.381  INFO 6664 --- [ost-startStop-1] o.s.b.w.servlet.FilterR
egistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-08-31 12:23:29.381  INFO 6664 --- [ost-startStop-1] o.s.b.w.servlet.FilterR
egistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-08-31 12:23:29.400  INFO 6664 --- [ost-startStop-1] .s.DelegatingFilterProx
yRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2018-08-31 12:23:29.400  INFO 6664 --- [ost-startStop-1] o.s.b.w.servlet.Servlet
RegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2018-08-31 12:23:35.199  INFO 6664 --- [           main] liquibase
                  : Successfully acquired change log lock
2018-08-31 12:23:37.304  INFO 6664 --- [           main] liquibase
                  : Reading from medi_client.DATABASECHANGELOG
2018-08-31 12:23:39.108  INFO 6664 --- [           main] liquibase
                  : Successfully released change log lock
2018-08-31 12:23:42.832  INFO 6664 --- [           main] j.LocalContainerEntityM
anagerFactoryBean : Building JPA container EntityManagerFactory for persistence
unit 'default'
2018-08-31 12:23:42.927  INFO 6664 --- [           main] o.hibernate.jpa.interna
l.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
        name: default
  ...]
2018-08-31 12:23:43.951  INFO 6664 --- [           main] org.hibernate.Version
                  : HHH000412: Hibernate Core {5.0.12.Final}
2018-08-31 12:23:43.954  INFO 6664 --- [           main] org.hibernate.cfg.Envir
onment            : HHH000206: hibernate.properties not found
2018-08-31 12:23:43.956  INFO 6664 --- [           main] org.hibernate.cfg.Envir
onment            : HHH000021: Bytecode provider name : javassist
2018-08-31 12:23:44.263  INFO 6664 --- [           main] o.hibernate.annotations
.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2018-08-31 12:23:45.305  INFO 6664 --- [           main] org.hibernate.dialect.D
ialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialec
t
2018-08-31 12:23:47.226  INFO 6664 --- [           main] j.LocalContainerEntityM
anagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'd
efault'
2018-08-31 12:23:48.447  INFO 6664 --- [           main] o.h.h.i.QueryTranslator
FactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
2018-08-31 12:23:48.998  WARN 6664 --- [           main] ationConfigEmbeddedWebA
pplicationContext : Exception encountered during context initialization - cancel
ling refresh attempt: org.springframework.beans.factory.BeanCreationException: E
rror creating bean with name 'bioScannerImpl' defined in URL [jar:file:/C:/Users
/SUYASH/Downloads/Compressed/code2.1/medical-gov/shared-library/build/libs/share
d-library-1.0.jar!/com/codesnbugs/shared/service/BioScannerImpl.class]: Bean ins
tantiation via constructor failed; nested exception is org.springframework.beans
.BeanInstantiationException: Failed to instantiate [com.codesnbugs.shared.servic
e.BioScannerImpl]: Constructor threw exception; nested exception is java.lang.Un
satisfiedLinkError: no CgtFpNative in java.library.path
2018-08-31 12:23:49.023  INFO 6664 --- [           main] j.LocalContainerEntityM
anagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'defau
lt'
2018-08-31 12:23:49.032  INFO 6664 --- [           main] o.apache.catalina.core.
StandardService   : Stopping service [Tomcat]
2018-08-31 12:23:49.251  INFO 6664 --- [           main] utoConfigurationReportL
oggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-r
un your application with 'debug' enabled.
2018-08-31 12:23:49.301 ERROR 6664 --- [           main] o.s.boot.SpringApplicat
ion               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean wit
h name 'bioScannerImpl' defined in URL [jar:file:/C:/Users/SUYASH/Downloads/Comp
ressed/code2.1/medical-gov/shared-library/build/libs/shared-library-1.0.jar!/com
/codesnbugs/shared/service/BioScannerImpl.class]: Bean instantiation via constru
ctor failed; nested exception is org.springframework.beans.BeanInstantiationExce
ption: Failed to instantiate [com.codesnbugs.shared.service.BioScannerImpl]: Con
structor threw exception; nested exception is java.lang.UnsatisfiedLinkError: no
 CgtFpNative in java.library.path
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:279) ~[spring-beans-4.3.13.RELEASE.jar:4.3
.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193) ~[spri
ng-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095) ~[sprin
g-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans
-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4
.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELE
ASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELE
ASE.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEAS
E]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]

        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3
.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-
4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar:4.3.1
3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationConte
xt.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.j
ar:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:693) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:360) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:303) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at com.codesnbugs.clientApp.Application.main(Application.java:29) [main/
:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to insta
ntiate [com.codesnbugs.shared.service.BioScannerImpl]: Constructor threw excepti
on; nested exception is java.lang.UnsatisfiedLinkError: no CgtFpNative in java.l
ibrary.path
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
54) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:122) ~[spring-beans-4.3.13.RELEASE
.jar:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:271) ~[spring-beans-4.3.13.RELEASE.jar:4.3
.13.RELEASE]
        ... 18 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: no CgtFpNative in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[na:1.8.0_1
61]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_161]
        at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_161]
        at Cogent.FpAccess.<clinit>(FpAccess.java:23) ~[CgtFpAccess-CSD200-Java.
jar:na]
        at Cogent.CgtFpCaptureAccess.cgtGetRunningInfo(CgtFpCaptureAccess.java:3
84) ~[CgtFpAccess-CSD200-Java.jar:na]
        at mmm.cogent.fpCaptureApi.MMMCogentCSD200DeviceImpl.isDeviceInitialized
(MMMCogentCSD200DeviceImpl.java:411) ~[CgtFpAccess-CSD200-Java.jar:na]
        at com.codesnbugs.shared.biometric.BioScanner.initialize(BioScanner.java
:25) ~[shared-library-1.0.jar:na]
        at com.codesnbugs.shared.service.BioScannerImpl.<init>(BioScannerImpl.ja
va:23) ~[shared-library-1.0.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 ~[na:1.8.0_161]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62) ~[na:1.8.0_161]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45) ~[na:1.8.0_161]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:
1.8.0_161]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
42) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        ... 20 common frames omitted

:client-app:bootRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client-app:bootRun'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_161\bin\java.exe'' finished w
ith non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 mins 59.381 secs

C:\Users\SUYASH\Downloads\Compressed\code2.1\medical-gov>

**Comment by serhatataman** [comment]
I am having same problem Suyash. How have you solved it?

**Comment by suyash796** [comment]
> I am having same problem Suyash. How have you solved it?

yes , i solved it 

 just try to install your softwares again and set the variable paths.

**Comment by amittal1** [comment]
Suyash, did you mean reinstall JAVA and gradle?
