### ISSUE TITLE
Custom View State through Activity recreation

### ISSUE THREAD

**Issue by sockeqwe** [frankiesardo/icepick#48]
I have a custom `LinearLayout` like this with `Mail extends Parcelable`:
```java
public class LabelLayout extends LinearLayout {
    @Icicle Mail mail;
}
```

```java
public class LabelLayout$$Icicle<T extends LabelLayout> extends View<T> {

  private final static Helper H = new Helper("com.hannesdorfmann.mosby.sample.mail.label.LabelLayout$$Icicle.");

  public Parcelable restore(T target, Parcelable p) {
    Bundle state = (Bundle) p;
    target.mail = H.getParcelable(state, "mail");
    return super.restore(target, H.getParent(state));
  }

  public Parcelable save(T target, Parcelable p) {
    Bundle state = H.putParent(super.save(target, p));
    H.putParcelable(state, "mail", target.mail);
    return state;
  }
}
```

Everything works like expected. However, if I turn "destroy activity" in the developer options on i get the following exception:
```
 Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@322c9bd9: Unmarshalling unknown type code 67 at offset 432
            at android.os.Parcel.readValue(Parcel.java:2222)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getParcelable(Bundle.java:804)
            at icepick.Injector$Helper.getParcelable(Injector.java:294)
            at com.hannesdorfmann.mosby.sample.mail.label.LabelLayout$$Icicle.restore(LabelLayout$$Icicle.java:14)
            at com.hannesdorfmann.mosby.sample.mail.label.LabelLayout$$Icicle.restore(LabelLayout$$Icicle.java:8)
            at icepick.Icepick.restoreInstanceState(Icepick.java:81)
            at com.hannesdorfmann.mosby.sample.mail.label.LabelLayout.onRestoreInstanceState(LabelLayout.java:169)
            at android.view.View.dispatchRestoreInstanceState(View.java:13621)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2887)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.View.restoreHierarchyState(View.java:13599)
            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:979)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1927)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

I'm not sure what the problem is, but as far as I see you using a bundle. However, `Bundle` is not persistent, while `PersistableBundle` is. I'm not sure if that solve the problem, just a hint where the problem may comes from.

**Comment by frankiesardo** [comment]
Interesting. Can I have a look at your `Mail` class? That's most likely the source of the problem.

**Comment by sockeqwe** [comment]
`Mail` class is correct, because I use it through `Intent`s without any problem.

However, I create my own `SavedState` in a super class and pass it to `Icepick.saveInstanceState(this, super.onSaveInstanceState());` etc.  I'm currently debbuging my `SavedState` and will come back to you with more information about it.

**Comment by sockeqwe** [comment]
Hi,
I'm really sorry, the error was not your fault!

It was my mistake!  Sorry for reporting!
